- name: Build kernel
  run: |
    export PATH="$HOME/toolchain/bin:$PATH"
    export ARCH=arm64
    export SUBARCH=arm64
    export CC=clang
    export HOSTCC=clang
    export HOSTCXX=clang++
    export LD=ld.lld
    export CLANG_TRIPLE=aarch64-linux-gnu-
    export CROSS_COMPILE=aarch64-linux-gnu-
    which clang
    clang --version
    make O=out ARCH=arm64 CC=clang HOSTCC=clang HOSTCXX=clang++ CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- blossom_defconfig
    make O=out ARCH=arm64 CC=clang HOSTCC=clang HOSTCXX=clang++ CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) Image.gz KCFLAGS="-w"
